A project for migrating issues from Apache Maven JIRA to GitHub.
It is based on the migration tool, that is written by the Spring Team, originally.

The code adjudgements, that was needed for the Apache Maven Project:

- create repository in organization is another REST API than create
repository in a user space
- Apache Jira has a path prefix in the URL
(https://issues.apache.org/jira). Currently, this fact has to be hardcoded.

Configuration changes:

- change application.properties to Maven Clean Plugin JIRA Project metadata
- add Application context Configuration for Maven Clean Plugin (needed
for label mapping etc)


## How to Guide

### Common Configuration

1. Adjust `application.properties` with the metadata of the Jira projet that should migrate
2. Configure the author mapping in `src/main/resources/jira-to-github-users.properties`
3. Create a Application context Configuration
[source, java]
----
@Configuration
@ConditionalOnProperty(name = "jira.projectId", havingValue = "yourProjectId")
public class MigrationConfig {


}
----

### Label Mapping

Add to your `MigrationConfig` class following beans:

[source, java]
----
	@Bean
	public LabelHandler labelHandler() {
		FieldValueLabelHandler fieldValueHandler = new FieldValueLabelHandler();
		fieldValueHandler.addMapping(FieldValueLabelHandler.FieldType.ISSUE_TYPE, "Bug", "bug");

		CompositeLabelHandler handler = new CompositeLabelHandler();
		handler.addLabelHandler(fieldValueHandler);


		return handler;
	}
----

`labelHandler` can be used for simple mapping logic.
If you need a mechanism where you can add more context information, you can implement an `IssuePorcessor`

[source, java]
----
	@Bean
	public IssueProcessor issueProcessor() {
		return new CompositeIssueProcessor(new FixDependencyIssueProcessor());
	}


	private static class FixDependencyIssueProcessor implements IssueProcessor {

		@Override
		public void beforeImport(JiraIssue jiraIssue, ImportGithubIssue githubIssue) {
			if (jiraIssue.getFields().getIssuetype().getName().equals("Task") ||
			jiraIssue.getFields().getIssuetype().getName().equals("Improvement")) {
				if(jiraIssue.getFields().getSummary().contains("Bump") || jiraIssue.getFields().getSummary().contains("Upgrade")) {
					githubIssue.getIssue().setLabels(List.of("dependencies"));
				}

			}

----
If you want to configure the desing of the Github Labels, you have to adjust the `LabelFactories` class.



## Original Content of the readme



A sample of the migration from Spring Security's JIRA to GitHub issues can be found at https://github.com/rwinch/spring-security-migrate-issues/issues[rwinch/spring-security-migrate-issues]
See `src/main/resources/application.properties` for settings. (based on the original code)

Some Key Features:

* Performs basic conversion from JIRA markup to GitHub markup
* Uses GitHub's experimental https://gist.github.com/jonmagic/5282384165e0f86ef105[import issue API] for increased speed and to keep dates accurate
* Links related issues
* Since GitHub issues does not allow for multiple fix versions, the migration creates a separate issue (called a backport issue) for each additional fix version and links to the original issue.
Each backport issue has a label named "Backport" on it so they can easily be found/filtered out.
* Each migrated issue has a Jira label added to it, so that if necessary the migration can be removed and performed again.
* Each issue has a link to the original JIRA issue
* Each comment has a link to the JIRA user profile of the original author
