# Guide: Service Account in GitHub

The migration tool needs an access token for calling the GitHub API.
You don't want to use your user account token, because then you are the author of all migrated issues.

This guide documents how to create service account in Github and how to generate access token for this service account for the special use case of migration tool.

## How to create a service account

In GitHub, a _Service Account_ is technically a GitHub App, that has permission for doing stuff in your user account or organisation. This how-to chapter is based on the blog post "Demystifying GitHub Apps: Using GitHub Apps to Replace Service Accounts" <<Blog Post Github App>>.

So we have to create a GitHub App:

NOTE: This guide explains how to create a GitHub App for an organisation.
This is only possible, if you have _Organization owner_ or _GitHub App manager_ permissions in your GitHub organization.

1. Navigate throught *Organization’s settings -> Developer Settings -> GitHub Apps -> New Github App*
2. Fill the details like name and URL (it is a mandatory field, but it is not needed for the migration steps).
3. Grant it the *permission*. In our case, we need only *repository permissions*:
    - Administration: Read Access (Read/Write Access, if you need to delete repositories for testing)
    - Issues: Read/Write Access
    - Pull Request: Read/Write Access
    - Metadata: Read-only Access
4. Create the GitHub App and save the shown *App ID*. It is needed in a later step.
5. Scroll down and generate a private key for the app. Save the generated private key. It is needed in a later step.
6. Scroll back and click on *Install App* to install the app to your organization. In this step, you have to decide, whether the app should have access to all repositories or only selected one.
7. After installation, pay attention the the URL in your browser. The last number in the URL is the *Installation ID*. Save it. It is needed in a later step.

Now, we have a service account in our organization. we should have a *private key*, a *App ID* and an *Installation ID*. These three items are needed for generating the access token for this service account.

## How to create an access token for a service account
This chapter based on the blog post "Making GitHub API Requests with a JWT" <<Blog Post Github JWT>> and the GitHub documentation <<Github Doc JWT>>.

In the above chapter, we created a service account.
At the end of the installation process, we create three items (*private key, App ID, Installation ID*).

These are needed for generating an access token:

1. We have to create a JWT based on the *private key* and *App ID*. JWT is needed to call a GitHub REST API, that is generated the access token. For JWT generation, we use a small CLI tool (jwt-creator) <<JWT Creator>>:
[source, shell]
----
export JWT=$(jwt-creator create --private-key-file private-key.pem --issued-at-now --expires-in-seconds 300 --issuer=<App ID>)
----

2. Call a GitHub REST API, that generate the access token.
[source, shell]
----
curl --request POST \
--url "https://api.github.com/app/installations/<Installation ID>/access_tokens" \
--header "Accept: application/vnd.github+json" \
--header "Authorization: Bearer $JWT" \
--header "X-GitHub-Api-Version: 2022-11-28"


{
  "token": "<your needed access token>",
  "expires_at": "2024-12-19T12:44:54Z",
  "permissions": {
    "administration": "write",
    "issues": "write",
    "metadata": "read"
  },
  "repository_selection": "all"
}

----

You can find the token in the response body (see value of the key `token`).

## Sources
- [[[Blog Post Github App,1]]] Blog Post "Demystifying GitHub Apps: Using GitHub Apps to Replace Service Accounts" Website: link:https://josh-ops.com/posts/github-apps/[]
- [[[Blog Post Github JWT,2]]] Blog Post "Making GitHub API Requests with a JWT" Website: link:https://trstringer.com/github-api-requests-with-jwt/[]
- [[[Github Doc JWT,3]]] GitHub Docs about "Generating an installation access token" Website: link:https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-an-installation-access-token-for-a-github-app#generating-an-installation-access-token[]
- [[[JWT Creator,4]]] CLI Tool `jwt-creator` Website: link:https://github.com/trstringer/jwt-creator[]
